### ISSUE TITLE
DRS testbed specification

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/cloud-interop-testing#62]
Outlining ideas here...

**Testbed targets:**

+ DRS endpoints
+ Test data objects
  + selected from a central library (like TRS/Dockstore)?
  + with pre-defined tests for data fidelity (like checker workflows)?

**Test procedures:**

+ Orchestrator makes `GET` requests to registered DRS endpoints to be evaluated in testbed
  + Validation of initial response
  + Attempt to retrieve bytes
  + Validation of retrieved object(s)
+ Other checks?

**Dependencies:**

+ DRS client

**Comment by briandoconnor** [comment]
@jaeddy I'm interested in helping out with this since it overlaps with what we did in NIH Data Commons

**Comment by jaeddy** [comment]
Closing this issue, as it's a bit too vague.
