### ISSUE TITLE
Update TRS/TES/WES/DRS READMEs to list known implementations 

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/cloud-interop-testing#63]
Recording implementations of APIs
* Can we review with the group on a future call?
* Go API by API and make sure the README has a list of known implementations
* We can take a first pass but need the API champions to confirm

**Comment by rishidev** [comment]
Should we do this in the Readme or have an implementations.md file to go with each repo?

**Comment by briandoconnor** [comment]
Angel suggests known working should be listed since it's in the README.

Look at Contributing or another place for development WIP implementations

**Comment by denis-yuen** [comment]
Update in progress for TRS at https://github.com/ga4gh/tool-registry-service-schemas/pull/115

**Comment by briandoconnor** [comment]
Good general practice but now we have the central GA4GH registry and should use that: https://docs.google.com/forms/d/e/1FAIpQLSfAyORmzrYkLSbQYxM9t-PANTDqrOpM6jv2G6bl7zvnk8egnw/viewform

Closing this
